# this is the version the bot will _probably_ pick up and PR.
{% set version = "3.1.0" %}
# Leave the build number the same if only the server version changes.
{% set build_number = 0 %}

# this will likely have to be hand-updated.
{% set server_version = "1.1.0" %}
# Leave the build number the same if only the labextension changes.
{% set server_build_number = 0 %}

# List of jupyter_lsp py.tests ran for each known servers
{% set server_tests = ["serverextension", "start_known", "listeners"] %}

package:
  name: jupyter-lsp-meta  # To avoid issue https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  - folder: jupyterlab-lsp
    url: https://pypi.io/packages/source/j/jupyterlab-lsp/jupyterlab-lsp-{{ version }}.tar.gz
    sha256: cfd6de7402a8333e807228a664560c74ff2ef74ecb38fefc98bcf7e2eb276ec7
  - folder: jupyter-lsp
    url: https://pypi.io/packages/source/j/jupyter-lsp/jupyter-lsp-{{ server_version }}.tar.gz
    sha256: eed95fa9a0ae6d4abb1203ccb04f64c4e4e707e5d19cc9b19bbf6651606af0e2

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo "TBD"

outputs:
  - name: jupyterlab-lsp
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script: cd jupyterlab-lsp && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - jupyter-lsp >={{ server_version }}
        - jupyterlab >=3,<4
        - python >=3.6
    test:
      requires:
        - pip
      commands:
        # TODO: restore after 1.0.0
        # - python -m pip check
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "jupyterlab-lsp.*OK.*jupyterlab_lsp"  # [unix]
    about:
      home: https://github.com/krassowski/jupyterlab-lsp
      license_file: jupyterlab-lsp/LICENSE
      license: BSD-3-Clause
      license_family: BSD
      summary: Language Server Protocol integration for JupyterLab
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/krassowski/jupyterlab-lsp/blob/master/docs

  - name: jupyter-lsp
    version: {{ server_version }}
    build:
      number: {{ server_build_number }}
      noarch: python
      script: cd jupyter-lsp && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - entrypoints
        - jupyter_server >={{ server_version }}
        - python >=3.6
    test:
      requires:
        - pip
      commands:
        - python -m pip check
        - jupyter server extension list
        - jupyter server extension list 1>serverextensions 2>&1
        - cat serverextensions | grep "jupyter_lsp.*OK"  # [unix]
    about:
      home: https://github.com/krassowski/jupyterlab-lsp
      license: BSD-3-Clause
      license_family: BSD
      license_file: jupyter-lsp/LICENSE
      summary: Multi-Language Server WebSocket proxy for Jupyter Server
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/krassowski/jupyterlab-lsp/blob/master/docs

  - name: jupyter-lsp-python
    version: {{ server_version }}
    build:
      number: {{ server_build_number }}
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("jupyter-lsp", exact=True) }}
        - python-language-server >=0.31.9
    test:
      requires:
        - pip
        - pytest-asyncio
        - pytest-runner
      commands:
        - python -m pip check
        # TODO add test for current ls by adding " or pyls" to -k option - but 1 test is failing
        - pytest -vv -p no:warnings --pyargs jupyter_lsp -k "not ({{ server_tests|join(' or ') }} or r_package_detection)"
    about:
      home: https://github.com/krassowski/jupyterlab-lsp
      license: BSD-3-Clause
      license_family: BSD
      license_file: jupyter-lsp/LICENSE
      summary: A metapackage for jupyter-lsp and python-language-server
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/krassowski/jupyterlab-lsp/blob/master/docs

  - name: jupyter-lsp-r
    version: {{ server_version }}
    build:
      number: {{ server_build_number }}
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("jupyter-lsp", exact=True) }}
        # Snippets support https://github.com/krassowski/jupyterlab-lsp/issues/208
        - r-languageserver >=0.3.5
    test:
      requires:
        - pip
        - pytest-asyncio
        - pytest-runner
      commands:
        - python -m pip check
        - pytest -vv -p no:warnings --pyargs jupyter_lsp -k "not ({{ server_tests|join(' or ') }})"
    about:
      home: https://github.com/krassowski/jupyterlab-lsp
      license: BSD-3-Clause
      license_family: BSD
      license_file: jupyter-lsp/LICENSE
      summary: A metapackage jupyter-lsp and r-languageserver
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/krassowski/jupyterlab-lsp/blob/master/docs


about:
  home: https://github.com/krassowski/jupyterlab-lsp
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupyterlab-lsp/LICENSE
  summary: Multi-Language Server WebSocket proxy for Jupyter Server
  doc_url: https://jupyterlab-lsp.readthedocs.io
  doc_source_url: https://github.com/krassowski/jupyterlab-lsp/blob/master/docs

extra:
  feedstock-name: jupyter-lsp
  recipe-maintainers:
    - bollwyvl
    - fcollonval
    - krassowski
